import Header from "./Components/Header/Header";
import Hero from "./Components/Hero/Hero";
import styles from "./page.module.css";
import Footer from "./Components/Footer/Footer";
import Hero3 from "./Components/Hero3/hero3";

// meta DAtA
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className={`${styles.background}`}>
        <Header />
        <Hero />
      </div>

      {/* section2 */}
      <section>
        <Hero3 />
      </section>

      <Footer />
    </>
  );
}
